In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [6]:
type(df)

pandas.DataFrame

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [8]:
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7037,2569-WGERO,Female,0,No,No,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No
2721,8225-BTJAU,Male,1,No,No,10,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,79.25,793.55,Yes
2212,8076-FEZKJ,Male,0,No,No,10,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,19.50,225.85,No
4228,6416-TVAIH,Male,0,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,68.50,68.5,Yes
3808,7785-RDVIG,Female,0,Yes,Yes,3,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.30,54.7,No

In [25]:
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"

tables = pd.read_html(
    url,
    storage_options={"User-Agent": "Mozilla/5.0"}
)

In [18]:
tables

[                                Location    Population % of world  \
 0                                  World  8.232000e+09       100%
 1                                  India  1.429404e+09      17.3%
 2                                  China  1.404890e+09      17.0%
 3                          United States  3.417849e+08       4.1%
 4                              Indonesia  2.883151e+08       3.5%
 ..                                   ...           ...        ...
 236         Christmas Island (Australia)  1.692000e+03         0%
 237                   Niue (New Zealand)  1.681000e+03         0%
 238                         Vatican City  8.820000e+02         0%
 239  Cocos (Keeling) Islands (Australia)  5.930000e+02         0%
 240                Pitcairn Islands (UK)  4.000000e+01         0%

             Date Source (official or from the United Nations) Notes
 0    13 Jun 2025                          UN projection[1][3]   NaN
 1     1 Jul 2026                       Official projection[4]   [b]
 2    31 Dec 2025                         Official estimate[5]   [c]
 3     1 Jul 2025                         Official estimate[6]   [d]
 4    31 Dec 2025                National annual projection[7]   NaN
 ..           ...                                          ...   ...
 236   1 Jan 2021                             2021 Census[248]   NaN
 237  11 Nov 2022                             2022 Census[249]   NaN
 238  31 Dec 2024                         Official figure[250]  [ah]
 239  30 Jun 2020                             2021 Census[251]   NaN
 240   1 Jul 2023                       Official estimate[252]   NaN

 [241 rows x 6 columns],
      vteLists of countries by population statistics  \
 0                                            Global
 1                             Continents/subregions
 2                                  Intercontinental
 3                                Cities/urban areas
 4                                   Past and future
 5                                Population density
 6                                 Growth indicators
 7                                   Life expectancy
 8                                Other demographics
 9                                            Health
 10                         Education and innovation
 11                                         Economic
 12  List of international rankings Lists by country

      vteLists of countries by population statistics.1
 0   Current population United Nations Demographics...
 1   Africa Antarctica Asia Europe North America Ca...
 2   Americas Arab world Commonwealth of Nations Eu...
 3   World cities National capitals Megacities Mega...
 4   Past and future population Estimates of histor...
 5   Current density Past and future population den...
 6   Population growth rate Natural increase Net re...
 7   World Africa Asia Europe North America Oceania...
 8   Age at childbearing Age at first marriage Age ...
 9   Antidepressant consumption Antiviral medicatio...
 10  Bloomberg Innovation Index Education Index Glo...
 11  Access to financial services Development aid d...
 12    List of international rankings Lists by country  ,
                                            vte World  \
 0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...

                                          vte World.1
 0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...  ]

In [17]:
type(tables)

list

In [16]:
len(tables)

3

In [19]:
tables[0]

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[248],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[249],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[250],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[251],NaN
240,Pitcairn Islands (UK),4.000000e+01,0%,1 Jul 2023,Official estimate[252],NaN

In [20]:
tables[1]

,vteLists of countries by population statistics,vteLists of countries by population statistics.1
0,Global,Current population United Nations Demographics...
1,Continents/subregions,Africa Antarctica Asia Europe North America Ca...
2,Intercontinental,Americas Arab world Commonwealth of Nations Eu...
3,Cities/urban areas,World cities National capitals Megacities Mega...
4,Past and future,Past and future population Estimates of histor...
5,Population density,Current density Past and future population den...
6,Growth indicators,Population growth rate Natural increase Net re...
7,Life expectancy,World Africa Asia Europe North America Oceania...
8,Other demographics,Age at childbearing Age at first marriage Age ...
9,Health,Antidepressant consumption Antiviral medicatio...
10,Education and innovation,Bloomberg Innovation Index Education Index Glo...
11,Economic,Access to financial services Development aid d...
12,List of international rankings Lists by country,List of international rankings Lists by country

In [21]:
tables[2]

,vte World,vte World.1
0,AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...,AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...

In [23]:
tables[0].to_csv("population_data.csv", index=False)

In [26]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"
df = pd.read_csv(url)

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df.shape

(891, 12)

In [29]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [31]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [33]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [40]:
string = []
for i in df.columns:
    if df[i].dtypes == "str":
        string.append(i)

string

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [ ]:
type(df[i])

In [41]:
df[string]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [42]:
df[string].describe()

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [43]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
df[df['Age'] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [50]:
df[(df['Age'] > 70) & (df["Sex"] == "male")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [51]:
data = {
    "name": [
        "Amit",
        "Priya",
        "Rahul",
        "Sneha",
        "Karan",
        "Neha"
    ],

    "age": [
        25,
        28,
        24,
        30,
        27,
        26
    ],

    "city": [
        "Bangalore",
        "Delhi",
        "Mumbai",
        "Bangalore",
        "Delhi",
        "Mumbai"
    ],

    "salary": [
        50000,
        65000,
        45000,
        75000,
        60000,
        55000
    ],

    "experience": [
        2,
        5,
        1,
        7,
        4,
        3
    ]
}

df = pd.DataFrame(data)

In [52]:
df

    name  age       city  salary  experience
0   Amit   25  Bangalore   50000           2
1  Priya   28      Delhi   65000           5
2  Rahul   24     Mumbai   45000           1
3  Sneha   30  Bangalore   75000           7
4  Karan   27      Delhi   60000           4
5   Neha   26     Mumbai   55000           3

In [56]:
df[(df["salary"]> 45000) & (df["experience"] >5)]

    name  age       city  salary  experience
3  Sneha   30  Bangalore   75000           7

In [57]:
df['bonus'] = df['salary'] * 0.10

In [58]:
df

    name  age       city  salary  experience   bonus
0   Amit   25  Bangalore   50000           2  5000.0
1  Priya   28      Delhi   65000           5  6500.0
2  Rahul   24     Mumbai   45000           1  4500.0
3  Sneha   30  Bangalore   75000           7  7500.0
4  Karan   27      Delhi   60000           4  6000.0
5   Neha   26     Mumbai   55000           3  5500.0

In [59]:
df['total_salary'] = df['salary']+ df['bonus']

In [60]:
df

    name  age       city  salary  experience   bonus  total_salary
0   Amit   25  Bangalore   50000           2  5000.0       55000.0
1  Priya   28      Delhi   65000           5  6500.0       71500.0
2  Rahul   24     Mumbai   45000           1  4500.0       49500.0
3  Sneha   30  Bangalore   75000           7  7500.0       82500.0
4  Karan   27      Delhi   60000           4  6000.0       66000.0
5   Neha   26     Mumbai   55000           3  5500.0       60500.0

In [61]:
df['salary'] = df['salary'] + 5000

In [62]:
df

    name  age       city  salary  experience   bonus  total_salary
0   Amit   25  Bangalore   55000           2  5000.0       55000.0
1  Priya   28      Delhi   70000           5  6500.0       71500.0
2  Rahul   24     Mumbai   50000           1  4500.0       49500.0
3  Sneha   30  Bangalore   80000           7  7500.0       82500.0
4  Karan   27      Delhi   65000           4  6000.0       66000.0
5   Neha   26     Mumbai   60000           3  5500.0       60500.0

In [ ]:
df.drop(columns = 'total_salary')

    name  age       city  salary  experience   bonus
0   Amit   25  Bangalore   55000           2  5000.0
1  Priya   28      Delhi   70000           5  6500.0
2  Rahul   24     Mumbai   50000           1  4500.0
3  Sneha   30  Bangalore   80000           7  7500.0
4  Karan   27      Delhi   65000           4  6000.0
5   Neha   26     Mumbai   60000           3  5500.0

In [64]:
df

    name  age       city  salary  experience   bonus  total_salary
0   Amit   25  Bangalore   55000           2  5000.0       55000.0
1  Priya   28      Delhi   70000           5  6500.0       71500.0
2  Rahul   24     Mumbai   50000           1  4500.0       49500.0
3  Sneha   30  Bangalore   80000           7  7500.0       82500.0
4  Karan   27      Delhi   65000           4  6000.0       66000.0
5   Neha   26     Mumbai   60000           3  5500.0       60500.0

In [ ]:
df.rename(
    columns = {
        "name": "employee_name"
    },
    inplace=True
)

In [66]:
df

  employee_name  age       city  salary  experience   bonus  total_salary
0          Amit   25  Bangalore   55000           2  5000.0       55000.0
1         Priya   28      Delhi   70000           5  6500.0       71500.0
2         Rahul   24     Mumbai   50000           1  4500.0       49500.0
3         Sneha   30  Bangalore   80000           7  7500.0       82500.0
4         Karan   27      Delhi   65000           4  6000.0       66000.0
5          Neha   26     Mumbai   60000           3  5500.0       60500.0

In [68]:
df.groupby('city')['salary'].mean()

city
Bangalore    67500.0
Delhi        67500.0
Mumbai       55000.0
Name: salary, dtype: float64

In [69]:
df.groupby('city')['salary'].sum()

city
Bangalore    135000
Delhi        135000
Mumbai       110000
Name: salary, dtype: int64

In [70]:
df.groupby('city')['salary'].agg(['mean', 'sum', 'min', 'max'])

              mean     sum    min    max
city
Bangalore  67500.0  135000  55000  80000
Delhi      67500.0  135000  65000  70000
Mumbai     55000.0  110000  50000  60000

In [71]:
df

  employee_name  age       city  salary  experience   bonus  total_salary
0          Amit   25  Bangalore   55000           2  5000.0       55000.0
1         Priya   28      Delhi   70000           5  6500.0       71500.0
2         Rahul   24     Mumbai   50000           1  4500.0       49500.0
3         Sneha   30  Bangalore   80000           7  7500.0       82500.0
4         Karan   27      Delhi   65000           4  6000.0       66000.0
5          Neha   26     Mumbai   60000           3  5500.0       60500.0

In [80]:
df.loc[0]

employee_name         Amit
age                     25
city             Bangalore
salary               55000
experience               2
bonus               5000.0
total_salary       55000.0
Name: 0, dtype: object

In [79]:
type(df.loc[0])

pandas.Series

In [81]:
df.loc[0:3]

  employee_name  age       city  salary  experience   bonus  total_salary
0          Amit   25  Bangalore   55000           2  5000.0       55000.0
1         Priya   28      Delhi   70000           5  6500.0       71500.0
2         Rahul   24     Mumbai   50000           1  4500.0       49500.0
3         Sneha   30  Bangalore   80000           7  7500.0       82500.0

In [82]:
df.loc[0:3, ['city', 'salary']]

        city  salary
0  Bangalore   55000
1      Delhi   70000
2     Mumbai   50000
3  Bangalore   80000

In [84]:
df.loc[[2,3], ['city', 'salary']]

        city  salary
2     Mumbai   50000
3  Bangalore   80000

In [85]:
students = pd.DataFrame({ "student_id": [1, 2, 3, 4], "name": ["Aman", "Rahul", "Priya", "Neha"] }) 

marks = pd.DataFrame({ "student_id": [1, 2, 3, 5], "marks": [85, 90, 78, 88] })

In [86]:
students

   student_id   name
0           1   Aman
1           2  Rahul
2           3  Priya
3           4   Neha

In [87]:
marks

   student_id  marks
0           1     85
1           2     90
2           3     78
3           5     88

In [90]:
pd.merge(students, marks, on="student_id", how="inner")

   student_id   name  marks
0           1   Aman     85
1           2  Rahul     90
2           3  Priya     78

In [91]:
pd.merge(students, marks, on="student_id", how="left")

   student_id   name  marks
0           1   Aman   85.0
1           2  Rahul   90.0
2           3  Priya   78.0
3           4   Neha    NaN

In [92]:
pd.merge(students, marks, on="student_id", how="right")

   student_id   name  marks
0           1   Aman     85
1           2  Rahul     90
2           3  Priya     78
3           5    NaN     88

In [93]:
pd.merge(students, marks, on="student_id", how="outer")

   student_id   name  marks
0           1   Aman   85.0
1           2  Rahul   90.0
2           3  Priya   78.0
3           4   Neha    NaN
4           5    NaN   88.0

In [95]:
pd.merge(students, marks, on="student_id", how="left", indicator=True)

   student_id   name  marks     _merge
0           1   Aman   85.0       both
1           2  Rahul   90.0       both
2           3  Priya   78.0       both
3           4   Neha    NaN  left_only

In [97]:
result = pd.merge(students, marks, on="student_id", how="left", indicator=True)
result[result["_merge"] == "left_only"]

   student_id  name  marks     _merge
3           4  Neha    NaN  left_only

In [99]:
df.sort_values('salary')

  employee_name  age       city  salary  experience   bonus  total_salary
2         Rahul   24     Mumbai   50000           1  4500.0       49500.0
0          Amit   25  Bangalore   55000           2  5000.0       55000.0
5          Neha   26     Mumbai   60000           3  5500.0       60500.0
4         Karan   27      Delhi   65000           4  6000.0       66000.0
1         Priya   28      Delhi   70000           5  6500.0       71500.0
3         Sneha   30  Bangalore   80000           7  7500.0       82500.0

In [100]:
df.sort_values('salary', ascending=False)

  employee_name  age       city  salary  experience   bonus  total_salary
3         Sneha   30  Bangalore   80000           7  7500.0       82500.0
1         Priya   28      Delhi   70000           5  6500.0       71500.0
4         Karan   27      Delhi   65000           4  6000.0       66000.0
5          Neha   26     Mumbai   60000           3  5500.0       60500.0
0          Amit   25  Bangalore   55000           2  5000.0       55000.0
2         Rahul   24     Mumbai   50000           1  4500.0       49500.0