In [38]:
import pandas as pd

In [39]:
# Read the dataset.
df = pd.read_csv('support_tickets.csv')

# Display first 5 rows of the df
df.head()

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
0,T001,Aarav Sharma,Payment,High,Resolved,Rahul,45
1,T002,Priya Patel,Technical,Critical,Open,Neha,120
2,T003,Rohan Mehta,Login,Medium,In Progress,Amit,75
3,T004,Ananya Shah,Course,Low,Closed,Priya,30
4,T005,Vikram Singh,Refund,High,Resolved,Rahul,90

In [40]:
# Find total tickets.
df.shape[0]

60

In [41]:
# Count tickets by category.
total_tickets = df['category'].value_counts()
total_tickets

category
Payment      10
Technical    10
Login        10
Course       10
Refund       10
Account      10
Name: count, dtype: int64

In [42]:
# Count tickets by priority.
total_priority = df['priority'].value_counts()
total_priority

priority
High        18
Medium      18
Critical    12
Low         12
Name: count, dtype: int64

In [43]:
# Count tickets by status.
total_status = df['status'].value_counts()
total_status

status
Resolved       24
Open           12
In Progress    12
Closed         12
Name: count, dtype: int64

In [44]:
# Find open tickets.
open_tickets = df[df['status'] == 'Open']
open_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
1,T002,Priya Patel,Technical,Critical,Open,Neha,120
5,T006,Neha Verma,Account,Medium,Open,Amit,150
11,T012,Ishita Rao,Account,Critical,Open,Priya,210
15,T016,Kavya Iyer,Course,Critical,Open,Priya,165
20,T021,Nikhil Jain,Login,Critical,Open,Rahul,200
25,T026,Muskan Arora,Technical,Critical,Open,Amit,240
30,T031,Suraj Yadav,Payment,Critical,Open,Neha,175
35,T036,Nandini Bose,Account,Critical,Open,Priya,190
40,T041,Manish Kumar,Refund,Critical,Open,Rahul,225
45,T046,Swati Ramesh,Course,Critical,Open,Amit,155
50,T051,Pranav Bhat,Login,Critical,Open,Neha,205
55,T056,Kirti Saini,Technical,High,Open,Priya,185

In [45]:
# Find critical tickets.
critical_tickets = df[df['priority'] == 'Critical']
critical_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
1,T002,Priya Patel,Technical,Critical,Open,Neha,120
6,T007,Karan Joshi,Payment,Critical,Resolved,Neha,180
11,T012,Ishita Rao,Account,Critical,Open,Priya,210
15,T016,Kavya Iyer,Course,Critical,Open,Priya,165
20,T021,Nikhil Jain,Login,Critical,Open,Rahul,200
25,T026,Muskan Arora,Technical,Critical,Open,Amit,240
30,T031,Suraj Yadav,Payment,Critical,Open,Neha,175
35,T036,Nandini Bose,Account,Critical,Open,Priya,190
40,T041,Manish Kumar,Refund,Critical,Open,Rahul,225
45,T046,Swati Ramesh,Course,Critical,Open,Amit,155
50,T051,Pranav Bhat,Login,Critical,Open,Neha,205
54,T055,Gaurav Bedi,Payment,Critical,Resolved,Neha,160

In [46]:
# Find resolved tickets.
resolved_tickets = df[df['status'] == 'Resolved']
resolved_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
0,T001,Aarav Sharma,Payment,High,Resolved,Rahul,45
4,T005,Vikram Singh,Refund,High,Resolved,Rahul,90
6,T007,Karan Joshi,Payment,Critical,Resolved,Neha,180
9,T010,Sneha Mehta,Course,Medium,Resolved,Amit,60
10,T011,Arjun Kapoor,Refund,High,Resolved,Neha,85
14,T015,Raj Malhotra,Login,High,Resolved,Neha,55
16,T017,Harsh Bansal,Refund,Medium,Resolved,Rahul,70
19,T020,Tanya Sethi,Technical,Medium,Resolved,Priya,80
21,T022,Riya Choudhary,Course,High,Resolved,Amit,100
24,T025,Sameer Kulkarni,Payment,High,Resolved,Rahul,65
26,T027,Abhinav Sinha,Login,Medium,Resolved,Neha,50
29,T030,Anjali Deshmukh,Account,Medium,Resolved,Amit,90
31,T032,Mahi Saxena,Technical,High,Resolved,Priya,105
34,T035,Deepak Chawla,Refund,High,Resolved,Neha,88
36,T037,Ritesh Kumar,Payment,Medium,Resolved,Rahul,72
39,T040,Ayesha Khan,Course,Medium,Resolved,Priya,62
41,T042,Vaishnavi Patil,Account,High,Resolved,Amit,98
44,T045,Chirag Shah,Login,High,Resolved,Rahul,58
46,T047,Akash Puri,Refund,Medium,Resolved,Neha,78
49,T050,Shalini Gupta,Technical,Medium,Resolved,Amit,82
51,T052,Juhi Vyas,Course,High,Resolved,Priya,92
54,T055,Gaurav Bedi,Payment,Critical,Resolved,Neha,160
56,T057,Abhay Desai,Login,Medium,Resolved,Rahul,68
59,T060,Preeti Nanda,Account,Medium,Resolved,Priya,86

In [47]:
# Find average resolution time.
average_resolution_time = round(df['resolution_time'].mean(), 2)
average_resolution_time

np.float64(100.37)

In [48]:
# Find average resolution time per category.
average_resolution_time_by_category = df.groupby('category')['resolution_time'].mean()
average_resolution_time_by_category

category
Account      124.8
Course        85.5
Login         87.6
Payment       96.2
Refund        95.2
Technical    112.9
Name: resolution_time, dtype: float64

In [49]:
# Find tickets handled by each support agent.

# Let's first check the unique support agents in the dataset.
unique_agents = df['assigned_agent'].unique()
unique_agents

<StringArray>
['Rahul', 'Neha', 'Amit', 'Priya']
Length: 4, dtype: str

In [50]:
# Find tickets handled by Rahul
rahul_tickets = df[df['assigned_agent'] == 'Rahul']
rahul_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
0,T001,Aarav Sharma,Payment,High,Resolved,Rahul,45
4,T005,Vikram Singh,Refund,High,Resolved,Rahul,90
8,T009,Aditya Shah,Login,Low,Closed,Rahul,25
12,T013,Manav Gupta,Payment,Medium,In Progress,Rahul,95
16,T017,Harsh Bansal,Refund,Medium,Resolved,Rahul,70
20,T021,Nikhil Jain,Login,Critical,Open,Rahul,200
24,T025,Sameer Kulkarni,Payment,High,Resolved,Rahul,65
28,T029,Varun Reddy,Refund,High,In Progress,Rahul,140
32,T033,Ayush Tiwari,Login,Low,Closed,Rahul,22
36,T037,Ritesh Kumar,Payment,Medium,Resolved,Rahul,72
40,T041,Manish Kumar,Refund,Critical,Open,Rahul,225
44,T045,Chirag Shah,Login,High,Resolved,Rahul,58
48,T049,Ankur Sood,Payment,High,In Progress,Rahul,108
52,T053,Omkar Sawant,Refund,Low,Closed,Rahul,24
56,T057,Abhay Desai,Login,Medium,Resolved,Rahul,68

In [51]:
# Find tickets handled by Neha
neha_tickets = df[df['assigned_agent'] == 'Neha']
neha_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
1,T002,Priya Patel,Technical,Critical,Open,Neha,120
6,T007,Karan Joshi,Payment,Critical,Resolved,Neha,180
10,T011,Arjun Kapoor,Refund,High,Resolved,Neha,85
14,T015,Raj Malhotra,Login,High,Resolved,Neha,55
18,T019,Yash Thakur,Payment,Low,Closed,Neha,35
22,T023,Dev Agarwal,Refund,Low,Closed,Neha,20
26,T027,Abhinav Sinha,Login,Medium,Resolved,Neha,50
30,T031,Suraj Yadav,Payment,Critical,Open,Neha,175
34,T035,Deepak Chawla,Refund,High,Resolved,Neha,88
38,T039,Siddharth Roy,Login,High,In Progress,Neha,118
42,T043,Abhishek Verma,Payment,Low,Closed,Neha,27
46,T047,Akash Puri,Refund,Medium,Resolved,Neha,78
50,T051,Pranav Bhat,Login,Critical,Open,Neha,205
54,T055,Gaurav Bedi,Payment,Critical,Resolved,Neha,160
58,T059,Raghav Arora,Refund,High,In Progress,Neha,132

In [52]:
# Find tickets handled by Amit
amit_tickets = df[df['assigned_agent'] == 'Amit']
amit_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
2,T003,Rohan Mehta,Login,Medium,In Progress,Amit,75
5,T006,Neha Verma,Account,Medium,Open,Amit,150
9,T010,Sneha Mehta,Course,Medium,Resolved,Amit,60
13,T014,Diya Nair,Technical,Low,Closed,Amit,40
17,T018,Simran Kaur,Account,High,In Progress,Amit,130
21,T022,Riya Choudhary,Course,High,Resolved,Amit,100
25,T026,Muskan Arora,Technical,Critical,Open,Amit,240
29,T030,Anjali Deshmukh,Account,Medium,Resolved,Amit,90
33,T034,Garima Mishra,Course,Medium,In Progress,Amit,125
37,T038,Palak Jain,Technical,Low,Closed,Amit,32
41,T042,Vaishnavi Patil,Account,High,Resolved,Amit,98
45,T046,Swati Ramesh,Course,Critical,Open,Amit,155
49,T050,Shalini Gupta,Technical,Medium,Resolved,Amit,82
53,T054,Leena Thomas,Account,Medium,In Progress,Amit,145
57,T058,Monika Pillai,Course,Low,Closed,Amit,38

In [53]:
# Find tickets handled by Priya
priya_tickets = df[df['assigned_agent'] == 'Priya']
priya_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
3,T004,Ananya Shah,Course,Low,Closed,Priya,30
7,T008,Meera Patel,Technical,High,In Progress,Priya,110
11,T012,Ishita Rao,Account,Critical,Open,Priya,210
15,T016,Kavya Iyer,Course,Critical,Open,Priya,165
19,T020,Tanya Sethi,Technical,Medium,Resolved,Priya,80
23,T024,Pooja Menon,Account,Medium,In Progress,Priya,115
27,T028,Shreya Das,Course,Low,Closed,Priya,28
31,T032,Mahi Saxena,Technical,High,Resolved,Priya,105
35,T036,Nandini Bose,Account,Critical,Open,Priya,190
39,T040,Ayesha Khan,Course,Medium,Resolved,Priya,62
43,T044,Sonali Dutta,Technical,Medium,In Progress,Priya,135
47,T048,Reema Joshi,Account,Low,Closed,Priya,34
51,T052,Juhi Vyas,Course,High,Resolved,Priya,92
55,T056,Kirti Saini,Technical,High,Open,Priya,185
59,T060,Preeti Nanda,Account,Medium,Resolved,Priya,86

In [54]:
# Sort tickets by resolution time.
sorted_tickets = df.sort_values(by='resolution_time', ascending=False)
sorted_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
25,T026,Muskan Arora,Technical,Critical,Open,Amit,240
40,T041,Manish Kumar,Refund,Critical,Open,Rahul,225
11,T012,Ishita Rao,Account,Critical,Open,Priya,210
50,T051,Pranav Bhat,Login,Critical,Open,Neha,205
20,T021,Nikhil Jain,Login,Critical,Open,Rahul,200
35,T036,Nandini Bose,Account,Critical,Open,Priya,190
55,T056,Kirti Saini,Technical,High,Open,Priya,185
6,T007,Karan Joshi,Payment,Critical,Resolved,Neha,180
30,T031,Suraj Yadav,Payment,Critical,Open,Neha,175
15,T016,Kavya Iyer,Course,Critical,Open,Priya,165
54,T055,Gaurav Bedi,Payment,Critical,Resolved,Neha,160
45,T046,Swati Ramesh,Course,Critical,Open,Amit,155
5,T006,Neha Verma,Account,Medium,Open,Amit,150
53,T054,Leena Thomas,Account,Medium,In Progress,Amit,145
28,T029,Varun Reddy,Refund,High,In Progress,Rahul,140
43,T044,Sonali Dutta,Technical,Medium,In Progress,Priya,135
58,T059,Raghav Arora,Refund,High,In Progress,Neha,132
17,T018,Simran Kaur,Account,High,In Progress,Amit,130
33,T034,Garima Mishra,Course,Medium,In Progress,Amit,125
1,T002,Priya Patel,Technical,Critical,Open,Neha,120
38,T039,Siddharth Roy,Login,High,In Progress,Neha,118
23,T024,Pooja Menon,Account,Medium,In Progress,Priya,115
7,T008,Meera Patel,Technical,High,In Progress,Priya,110
48,T049,Ankur Sood,Payment,High,In Progress,Rahul,108
31,T032,Mahi Saxena,Technical,High,Resolved,Priya,105
21,T022,Riya Choudhary,Course,High,Resolved,Amit,100
41,T042,Vaishnavi Patil,Account,High,Resolved,Amit,98
12,T013,Manav Gupta,Payment,Medium,In Progress,Rahul,95
51,T052,Juhi Vyas,Course,High,Resolved,Priya,92
29,T030,Anjali Deshmukh,Account,Medium,Resolved,Amit,90
4,T005,Vikram Singh,Refund,High,Resolved,Rahul,90
34,T035,Deepak Chawla,Refund,High,Resolved,Neha,88
59,T060,Preeti Nanda,Account,Medium,Resolved,Priya,86
10,T011,Arjun Kapoor,Refund,High,Resolved,Neha,85
49,T050,Shalini Gupta,Technical,Medium,Resolved,Amit,82
19,T020,Tanya Sethi,Technical,Medium,Resolved,Priya,80
46,T047,Akash Puri,Refund,Medium,Resolved,Neha,78
2,T003,Rohan Mehta,Login,Medium,In Progress,Amit,75
36,T037,Ritesh Kumar,Payment,Medium,Resolved,Rahul,72
16,T017,Harsh Bansal,Refund,Medium,Resolved,Rahul,70
56,T057,Abhay Desai,Login,Medium,Resolved,Rahul,68
24,T025,Sameer Kulkarni,Payment,High,Resolved,Rahul,65
39,T040,Ayesha Khan,Course,Medium,Resolved,Priya,62
9,T010,Sneha Mehta,Course,Medium,Resolved,Amit,60
44,T045,Chirag Shah,Login,High,Resolved,Rahul,58
14,T015,Raj Malhotra,Login,High,Resolved,Neha,55
26,T027,Abhinav Sinha,Login,Medium,Resolved,Neha,50
0,T001,Aarav Sharma,Payment,High,Resolved,Rahul,45
13,T014,Diya Nair,Technical,Low,Closed,Amit,40
57,T058,Monika Pillai,Course,Low,Closed,Amit,38
18,T019,Yash Thakur,Payment,Low,Closed,Neha,35
47,T048,Reema Joshi,Account,Low,Closed,Priya,34
37,T038,Palak Jain,Technical,Low,Closed,Amit,32
3,T004,Ananya Shah,Course,Low,Closed,Priya,30
27,T028,Shreya Das,Course,Low,Closed,Priya,28
42,T043,Abhishek Verma,Payment,Low,Closed,Neha,27
8,T009,Aditya Shah,Login,Low,Closed,Rahul,25
52,T053,Omkar Sawant,Refund,Low,Closed,Rahul,24
32,T033,Ayush Tiwari,Login,Low,Closed,Rahul,22
22,T023,Dev Agarwal,Refund,Low,Closed,Neha,20

In [55]:
# Find tickets taking maximum resolution time.
max_resolution_time = df['resolution_time'].max()
max_resolution_tickets = df[df['resolution_time'] == max_resolution_time]
max_resolution_tickets

,ticket_id,customer_name,category,priority,status,assigned_agent,resolution_time
25,T026,Muskan Arora,Technical,Critical,Open,Amit,240

In [65]:
# Create a summary report of the tickets.
ticket_summary_report = {
    "total_tickets": len(df),
    "average_resolution_time": average_resolution_time,
    "max_resolution_time": max_resolution_time,
    "open_tickets": len(open_tickets),
    "critical_tickets": len(critical_tickets),
    "resolved_tickets": len(resolved_tickets),
    "rahul_tickets": len(rahul_tickets),
    "neha_tickets": len(neha_tickets),
    "amit_tickets": len(amit_tickets),
    "priya_tickets": len(priya_tickets)
}

# Convert the summary report to a DataFrame
ticket_summary = pd.DataFrame(list(ticket_summary_report.items()), columns=['Metric', 'Value'])
ticket_summary

                    Metric   Value
0            total_tickets   60.00
1  average_resolution_time  100.37
2      max_resolution_time  240.00
3             open_tickets   12.00
4         critical_tickets   12.00
5         resolved_tickets   24.00
6            rahul_tickets   15.00
7             neha_tickets   15.00
8             amit_tickets   15.00
9            priya_tickets   15.00

In [66]:
# Export the summary report to a CSV file.
ticket_summary.to_csv('ticket_summary.csv', index=False)