In [1]:
import pandas as pd

In [3]:
# Read csv
df = pd.read_csv("products.csv")

In [4]:
# Inspect dataset.
df.head()

,product_id,product_name,category,brand,price,rating,stock,discount
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10

In [9]:
# Find total products.
df.shape[0]

60

In [10]:
# Find unique categories.
df['category'].nunique()

7

In [11]:
# Find unique brands.
df['brand'].nunique()

13

In [18]:
# Count products category-wise.
df.groupby('category')["product_name"].count()

category
Accessories     8
Headphones      8
Keyboard        8
Laptop         10
Mobile         10
Monitor         8
Tablet          8
Name: product_name, dtype: int64

In [19]:
# Find average price.
df['price'].mean()

np.float64(46020.7)

In [20]:
# Find highest-priced product.
df[df['price'] == df['price'].max()]

  product_id    product_name category  brand   price  rating  stock  discount
5       P006  MacBook Pro 14   Laptop  Apple  169999     4.9      4         7

In [21]:
# Find lowest-priced product.
df[df['price'] == df['price'].min()]

,product_id,product_name,category,brand,price,rating,stock,discount
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20

In [22]:
# Find products priced above ₹50,000.
df[df['price'] > 50000]

,product_id,product_name,category,brand,price,rating,stock,discount
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8

In [23]:
# Find products with rating greater than 4.
df[df['rating'] > 4]

,product_id,product_name,category,brand,price,rating,stock,discount
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12
14,P015,Nothing Phone 2,Mobile,Nothing,44999,4.3,25,15
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6
16,P017,Samsung Galaxy A55,Mobile,Samsung,39999,4.4,21,11
17,P018,OnePlus Nord 4,Mobile,OnePlus,32999,4.5,16,9
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10
20,P021,Sony WH-1000XM5,Headphones,Sony,29999,4.8,14,15
21,P022,Apple AirPods Pro 2,Headphones,Apple,24999,4.7,20,8
22,P023,Samsung Galaxy Buds2 Pro,Headphones,Samsung,13999,4.5,24,12
23,P024,OnePlus Buds Pro 2,Headphones,OnePlus,11999,4.4,17,10
24,P025,Logitech Zone Vibe 100,Headphones,Logitech,8999,4.2,13,18
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9
26,P027,Apple AirPods 3,Headphones,Apple,18999,4.6,26,7
27,P028,Google Pixel Buds Pro,Headphones,Google,17999,4.3,12,14
28,P029,Logitech K380,Keyboard,Logitech,2999,4.5,35,20
29,P030,Keychron K2,Keyboard,Keychron,7499,4.7,16,12
30,P031,Apple Magic Keyboard,Keyboard,Apple,10999,4.4,10,8
31,P032,ASUS TUF Gaming K3,Keyboard,ASUS,5999,4.3,18,15
32,P033,HP Wireless Keyboard,Keyboard,HP,2499,4.1,29,18
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10
34,P035,Dell Premier Keyboard,Keyboard,Dell,4999,4.2,14,13
35,P036,Lenovo Professional Keyboard,Keyboard,Lenovo,3499,4.3,22,16
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11
37,P038,LG UltraGear 27GN800,Monitor,LG,32999,4.6,11,14
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9
40,P041,HP M27fq,Monitor,HP,21999,4.2,15,18
41,P042,Lenovo ThinkVision T24i,Monitor,Lenovo,19999,4.3,13,12
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12
46,P047,OnePlus Pad 2,Tablet,OnePlus,39999,4.5,14,10
47,P048,Lenovo Tab P12,Tablet,Lenovo,29999,4.3,19,15
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8
50,P051,Apple iPad 10th Gen,Tablet,Apple,38999,4.6,17,11
51,P052,Samsung Galaxy Tab A9,Tablet,Samsung,17999,4.2,28,16
52,P053,Logitech MX Master 3S,Accessories,Logitech,8999,4.8,21,14
53,P054,Apple MagSafe Charger,Accessories,Apple,4499,4.5,30,10
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20
55,P056,OnePlus Power Bank,Accessories,OnePlus,1999,4.3,27,18
56,P057,Dell USB-C Hub,Accessories,Dell,3999,4.2,16,15
57,P058,HP Laptop Backpack,Accessories,HP,2999,4.1,25,22
58,P059,Lenovo Wireless Mouse,Accessories,Lenovo,1799,4.3,33,17
59,P060,ASUS USB-C Dock,Accessories,ASUS,6999,4.4,12,13

In [24]:
# Sort products by price.
df.sort_values(by='price', ascending=False)

,product_id,product_name,category,brand,price,rating,stock,discount
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13
14,P015,Nothing Phone 2,Mobile,Nothing,44999,4.3,25,15
46,P047,OnePlus Pad 2,Tablet,OnePlus,39999,4.5,14,10
16,P017,Samsung Galaxy A55,Mobile,Samsung,39999,4.4,21,11
50,P051,Apple iPad 10th Gen,Tablet,Apple,38999,4.6,17,11
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9
17,P018,OnePlus Nord 4,Mobile,OnePlus,32999,4.5,16,9
37,P038,LG UltraGear 27GN800,Monitor,LG,32999,4.6,11,14
47,P048,Lenovo Tab P12,Tablet,Lenovo,29999,4.3,19,15
20,P021,Sony WH-1000XM5,Headphones,Sony,29999,4.8,14,15
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9
21,P022,Apple AirPods Pro 2,Headphones,Apple,24999,4.7,20,8
40,P041,HP M27fq,Monitor,HP,21999,4.2,15,18
41,P042,Lenovo ThinkVision T24i,Monitor,Lenovo,19999,4.3,13,12
26,P027,Apple AirPods 3,Headphones,Apple,18999,4.6,26,7
27,P028,Google Pixel Buds Pro,Headphones,Google,17999,4.3,12,14
51,P052,Samsung Galaxy Tab A9,Tablet,Samsung,17999,4.2,28,16
22,P023,Samsung Galaxy Buds2 Pro,Headphones,Samsung,13999,4.5,24,12
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10
23,P024,OnePlus Buds Pro 2,Headphones,OnePlus,11999,4.4,17,10
30,P031,Apple Magic Keyboard,Keyboard,Apple,10999,4.4,10,8
24,P025,Logitech Zone Vibe 100,Headphones,Logitech,8999,4.2,13,18
52,P053,Logitech MX Master 3S,Accessories,Logitech,8999,4.8,21,14
29,P030,Keychron K2,Keyboard,Keychron,7499,4.7,16,12
59,P060,ASUS USB-C Dock,Accessories,ASUS,6999,4.4,12,13
31,P032,ASUS TUF Gaming K3,Keyboard,ASUS,5999,4.3,18,15
34,P035,Dell Premier Keyboard,Keyboard,Dell,4999,4.2,14,13
53,P054,Apple MagSafe Charger,Accessories,Apple,4499,4.5,30,10
56,P057,Dell USB-C Hub,Accessories,Dell,3999,4.2,16,15
35,P036,Lenovo Professional Keyboard,Keyboard,Lenovo,3499,4.3,22,16
57,P058,HP Laptop Backpack,Accessories,HP,2999,4.1,25,22
28,P029,Logitech K380,Keyboard,Logitech,2999,4.5,35,20
32,P033,HP Wireless Keyboard,Keyboard,HP,2499,4.1,29,18
55,P056,OnePlus Power Bank,Accessories,OnePlus,1999,4.3,27,18
58,P059,Lenovo Wireless Mouse,Accessories,Lenovo,1799,4.3,33,17
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20

In [25]:
# Sort products by rating.
df.sort_values(by='rating', ascending=False)

,product_id,product_name,category,brand,price,rating,stock,discount
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
20,P021,Sony WH-1000XM5,Headphones,Sony,29999,4.8,14,15
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6
52,P053,Logitech MX Master 3S,Accessories,Logitech,8999,4.8,21,14
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5
21,P022,Apple AirPods Pro 2,Headphones,Apple,24999,4.7,20,8
29,P030,Keychron K2,Keyboard,Keychron,7499,4.7,16,12
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10
37,P038,LG UltraGear 27GN800,Monitor,LG,32999,4.6,11,14
50,P051,Apple iPad 10th Gen,Tablet,Apple,38999,4.6,17,11
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10
26,P027,Apple AirPods 3,Headphones,Apple,18999,4.6,26,7
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9
22,P023,Samsung Galaxy Buds2 Pro,Headphones,Samsung,13999,4.5,24,12
17,P018,OnePlus Nord 4,Mobile,OnePlus,32999,4.5,16,9
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8
46,P047,OnePlus Pad 2,Tablet,OnePlus,39999,4.5,14,10
53,P054,Apple MagSafe Charger,Accessories,Apple,4499,4.5,30,10
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10
28,P029,Logitech K380,Keyboard,Logitech,2999,4.5,35,20
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20
59,P060,ASUS USB-C Dock,Accessories,ASUS,6999,4.4,12,13
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9
30,P031,Apple Magic Keyboard,Keyboard,Apple,10999,4.4,10,8
16,P017,Samsung Galaxy A55,Mobile,Samsung,39999,4.4,21,11
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12
23,P024,OnePlus Buds Pro 2,Headphones,OnePlus,11999,4.4,17,10
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8
27,P028,Google Pixel Buds Pro,Headphones,Google,17999,4.3,12,14
14,P015,Nothing Phone 2,Mobile,Nothing,44999,4.3,25,15
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13
58,P059,Lenovo Wireless Mouse,Accessories,Lenovo,1799,4.3,33,17
47,P048,Lenovo Tab P12,Tablet,Lenovo,29999,4.3,19,15
55,P056,OnePlus Power Bank,Accessories,OnePlus,1999,4.3,27,18
41,P042,Lenovo ThinkVision T24i,Monitor,Lenovo,19999,4.3,13,12
31,P032,ASUS TUF Gaming K3,Keyboard,ASUS,5999,4.3,18,15
35,P036,Lenovo Professional Keyboard,Keyboard,Lenovo,3499,4.3,22,16
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15
56,P057,Dell USB-C Hub,Accessories,Dell,3999,4.2,16,15
24,P025,Logitech Zone Vibe 100,Headphones,Logitech,8999,4.2,13,18
34,P035,Dell Premier Keyboard,Keyboard,Dell,4999,4.2,14,13
40,P041,HP M27fq,Monitor,HP,21999,4.2,15,18
51,P052,Samsung Galaxy Tab A9,Tablet,Samsung,17999,4.2,28,16
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10
32,P033,HP Wireless Keyboard,Keyboard,HP,2499,4.1,29,18
57,P058,HP Laptop Backpack,Accessories,HP,2999,4.1,25,22

In [26]:
# Find products with stock below 10.
df[df['stock'] < 10]

,product_id,product_name,category,brand,price,rating,stock,discount
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8

In [29]:
# Create discount_amount.
df['discount_amount'] = df['price'] * (df['discount'] / 100)
df

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10,8999.90
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12,15000.00
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8,5199.92
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15,8849.85
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10,14500.00
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7,11899.93
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10,5599.90
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13,10269.87
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9,10349.91
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14,8679.86
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5,3499.95
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8,5999.92
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10,5999.90
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12,7919.88
14,P015,Nothing Phone 2,Mobile,Nothing,44999,4.3,25,15,6749.85
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6,7799.94
16,P017,Samsung Galaxy A55,Mobile,Samsung,39999,4.4,21,11,4399.89
17,P018,OnePlus Nord 4,Mobile,OnePlus,32999,4.5,16,9,2969.91
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13,6889.87
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10,9999.90
20,P021,Sony WH-1000XM5,Headphones,Sony,29999,4.8,14,15,4499.85
21,P022,Apple AirPods Pro 2,Headphones,Apple,24999,4.7,20,8,1999.92
22,P023,Samsung Galaxy Buds2 Pro,Headphones,Samsung,13999,4.5,24,12,1679.88
23,P024,OnePlus Buds Pro 2,Headphones,OnePlus,11999,4.4,17,10,1199.90
24,P025,Logitech Zone Vibe 100,Headphones,Logitech,8999,4.2,13,18,1619.82
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9,2519.91
26,P027,Apple AirPods 3,Headphones,Apple,18999,4.6,26,7,1329.93
27,P028,Google Pixel Buds Pro,Headphones,Google,17999,4.3,12,14,2519.86
28,P029,Logitech K380,Keyboard,Logitech,2999,4.5,35,20,599.80
29,P030,Keychron K2,Keyboard,Keychron,7499,4.7,16,12,899.88
30,P031,Apple Magic Keyboard,Keyboard,Apple,10999,4.4,10,8,879.92
31,P032,ASUS TUF Gaming K3,Keyboard,ASUS,5999,4.3,18,15,899.85
32,P033,HP Wireless Keyboard,Keyboard,HP,2499,4.1,29,18,449.82
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10,1299.90
34,P035,Dell Premier Keyboard,Keyboard,Dell,4999,4.2,14,13,649.87
35,P036,Lenovo Professional Keyboard,Keyboard,Lenovo,3499,4.3,22,16,559.84
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11,6049.89
37,P038,LG UltraGear 27GN800,Monitor,LG,32999,4.6,11,14,4619.86
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16,4639.84
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9,3419.91
40,P041,HP M27fq,Monitor,HP,21999,4.2,15,18,3959.82
41,P042,Lenovo ThinkVision T24i,Monitor,Lenovo,19999,4.3,13,12,2399.88
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5,7999.95
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10,5699.90
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7,4199.93
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12,8999.88
46,P047,OnePlus Pad 2,Tablet,OnePlus,39999,4.5,14,10,3999.90
47,P048,Lenovo Tab P12,Tablet,Lenovo,29999,4.3,19,15,4499.85
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9,6119.91
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8,11199.92
50,P051,Apple iPad 10th Gen,Tablet,Apple,38999,4.6,17,11,4289.89
51,P052,Samsung Galaxy Tab A9,Tablet,Samsung,17999,4.2,28,16,2879.84
52,P053,Logitech MX Master 3S,Accessories,Logitech,8999,4.8,21,14,1259.86
53,P054,Apple MagSafe Charger,Accessories,Apple,4499,4.5,30,10,449.90
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20,299.80
55,P056,OnePlus Power Bank,Accessories,OnePlus,1999,4.3,27,18,359.82
56,P057,Dell USB-C Hub,Accessories,Dell,3999,4.2,16,15,599.85
57,P058,HP Laptop Backpack,Accessories,HP,2999,4.1,25,22,659.78
58,P059,Lenovo Wireless Mouse,Accessories,Lenovo,1799,4.3,33,17,305.83
59,P060,ASUS USB-C Dock,Accessories,ASUS,6999,4.4,12,13,909.87

In [30]:
# Create final_price.
df['final_price'] = df['price'] - df['discount_amount']
df

,product_id,product_name,category,brand,price,rating,stock,discount,discount_amount,final_price
0,P001,MacBook Air M3,Laptop,Apple,89999,4.8,8,10,8999.90,80999.10
1,P002,Dell XPS 15,Laptop,Dell,125000,4.7,5,12,15000.00,110000.00
2,P003,HP Pavilion 15,Laptop,HP,64999,4.3,15,8,5199.92,59799.08
3,P004,Lenovo IdeaPad Slim 5,Laptop,Lenovo,58999,4.2,22,15,8849.85,50149.15
4,P005,ASUS ROG Strix,Laptop,ASUS,145000,4.6,6,10,14500.00,130500.00
5,P006,MacBook Pro 14,Laptop,Apple,169999,4.9,4,7,11899.93,158099.07
6,P007,Dell Inspiron 14,Laptop,Dell,55999,4.1,19,10,5599.90,50399.10
7,P008,HP Envy x360,Laptop,HP,78999,4.4,11,13,10269.87,68729.13
8,P009,Lenovo Legion 5,Laptop,Lenovo,114999,4.5,7,9,10349.91,104649.09
9,P010,ASUS VivoBook 15,Laptop,ASUS,61999,4.2,18,14,8679.86,53319.14
10,P011,iPhone 15,Mobile,Apple,69999,4.7,12,5,3499.95,66499.05
11,P012,Samsung Galaxy S24,Mobile,Samsung,74999,4.6,9,8,5999.92,68999.08
12,P013,OnePlus 12,Mobile,OnePlus,59999,4.5,18,10,5999.90,53999.10
13,P014,Google Pixel 8,Mobile,Google,65999,4.4,7,12,7919.88,58079.12
14,P015,Nothing Phone 2,Mobile,Nothing,44999,4.3,25,15,6749.85,38249.15
15,P016,iPhone 15 Pro,Mobile,Apple,129999,4.8,6,6,7799.94,122199.06
16,P017,Samsung Galaxy A55,Mobile,Samsung,39999,4.4,21,11,4399.89,35599.11
17,P018,OnePlus Nord 4,Mobile,OnePlus,32999,4.5,16,9,2969.91,30029.09
18,P019,Google Pixel 8a,Mobile,Google,52999,4.3,10,13,6889.87,46109.13
19,P020,Samsung Galaxy Z Flip 5,Mobile,Samsung,99999,4.6,5,10,9999.90,89999.10
20,P021,Sony WH-1000XM5,Headphones,Sony,29999,4.8,14,15,4499.85,25499.15
21,P022,Apple AirPods Pro 2,Headphones,Apple,24999,4.7,20,8,1999.92,22999.08
22,P023,Samsung Galaxy Buds2 Pro,Headphones,Samsung,13999,4.5,24,12,1679.88,12319.12
23,P024,OnePlus Buds Pro 2,Headphones,OnePlus,11999,4.4,17,10,1199.90,10799.10
24,P025,Logitech Zone Vibe 100,Headphones,Logitech,8999,4.2,13,18,1619.82,7379.18
25,P026,Sony WF-1000XM5,Headphones,Sony,27999,4.6,8,9,2519.91,25479.09
26,P027,Apple AirPods 3,Headphones,Apple,18999,4.6,26,7,1329.93,17669.07
27,P028,Google Pixel Buds Pro,Headphones,Google,17999,4.3,12,14,2519.86,15479.14
28,P029,Logitech K380,Keyboard,Logitech,2999,4.5,35,20,599.80,2399.20
29,P030,Keychron K2,Keyboard,Keychron,7499,4.7,16,12,899.88,6599.12
30,P031,Apple Magic Keyboard,Keyboard,Apple,10999,4.4,10,8,879.92,10119.08
31,P032,ASUS TUF Gaming K3,Keyboard,ASUS,5999,4.3,18,15,899.85,5099.15
32,P033,HP Wireless Keyboard,Keyboard,HP,2499,4.1,29,18,449.82,2049.18
33,P034,Logitech G Pro X Keyboard,Keyboard,Logitech,12999,4.6,9,10,1299.90,11699.10
34,P035,Dell Premier Keyboard,Keyboard,Dell,4999,4.2,14,13,649.87,4349.13
35,P036,Lenovo Professional Keyboard,Keyboard,Lenovo,3499,4.3,22,16,559.84,2939.16
36,P037,Dell UltraSharp U2723QE,Monitor,Dell,54999,4.7,6,11,6049.89,48949.11
37,P038,LG UltraGear 27GN800,Monitor,LG,32999,4.6,11,14,4619.86,28379.14
38,P039,Samsung Odyssey G5,Monitor,Samsung,28999,4.5,8,16,4639.84,24359.16
39,P040,ASUS ProArt PA278QV,Monitor,ASUS,37999,4.4,7,9,3419.91,34579.09
40,P041,HP M27fq,Monitor,HP,21999,4.2,15,18,3959.82,18039.18
41,P042,Lenovo ThinkVision T24i,Monitor,Lenovo,19999,4.3,13,12,2399.88,17599.12
42,P043,Apple Studio Display,Monitor,Apple,159999,4.8,3,5,7999.95,151999.05
43,P044,Samsung Smart Monitor M8,Monitor,Samsung,56999,4.5,5,10,5699.90,51299.10
44,P045,Apple iPad Air,Tablet,Apple,59999,4.7,9,7,4199.93,55799.07
45,P046,Samsung Galaxy Tab S9,Tablet,Samsung,74999,4.6,8,12,8999.88,65999.12
46,P047,OnePlus Pad 2,Tablet,OnePlus,39999,4.5,14,10,3999.90,35999.10
47,P048,Lenovo Tab P12,Tablet,Lenovo,29999,4.3,19,15,4499.85,25499.15
48,P049,Google Pixel Tablet,Tablet,Google,67999,4.4,6,9,6119.91,61879.09
49,P050,ASUS ROG Flow Z13,Tablet,ASUS,139999,4.5,4,8,11199.92,128799.08
50,P051,Apple iPad 10th Gen,Tablet,Apple,38999,4.6,17,11,4289.89,34709.11
51,P052,Samsung Galaxy Tab A9,Tablet,Samsung,17999,4.2,28,16,2879.84,15119.16
52,P053,Logitech MX Master 3S,Accessories,Logitech,8999,4.8,21,14,1259.86,7739.14
53,P054,Apple MagSafe Charger,Accessories,Apple,4499,4.5,30,10,449.90,4049.10
54,P055,Samsung 25W Charger,Accessories,Samsung,1499,4.4,42,20,299.80,1199.20
55,P056,OnePlus Power Bank,Accessories,OnePlus,1999,4.3,27,18,359.82,1639.18
56,P057,Dell USB-C Hub,Accessories,Dell,3999,4.2,16,15,599.85,3399.15
57,P058,HP Laptop Backpack,Accessories,HP,2999,4.1,25,22,659.78,2339.22
58,P059,Lenovo Wireless Mouse,Accessories,Lenovo,1799,4.3,33,17,305.83,1493.17
59,P060,ASUS USB-C Dock,Accessories,ASUS,6999,4.4,12,13,909.87,6089.13

In [31]:
# Find average price by category.
df.groupby('category')['price'].mean()

category
Accessories     4099.0
Headphones     19374.0
Keyboard        6436.5
Laptop         96599.2
Mobile         67199.0
Monitor        51749.0
Tablet         58749.0
Name: price, dtype: float64

In [32]:
# Find average rating by brand.
df.groupby('brand')['rating'].mean()

brand
ASUS        4.400000
Apple       4.681818
Dell        4.380000
Google      4.350000
HP          4.220000
Keychron    4.700000
LG          4.600000
Lenovo      4.316667
Logitech    4.525000
Nothing     4.300000
OnePlus     4.440000
Samsung     4.477778
Sony        4.700000
Name: rating, dtype: float64

In [33]:
# Find maximum product price category-wise.
df.groupby('category')['price'].max()

category
Accessories      8999
Headphones      29999
Keyboard        12999
Laptop         169999
Mobile         129999
Monitor        159999
Tablet         139999
Name: price, dtype: int64

In [34]:
# Export final data.
df.to_csv("output/products_final.csv", index=False)