In [1]:
import pandas as pd

In [2]:
# Read CSV file
df = pd.read_csv('students.csv')
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
2,ST003,Rahul Verma,20,Delhi,76,81,73,79
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
4,ST005,Arjun Mehta,21,Pune,67,72,69,74
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85
7,ST008,Meera Iyer,21,Chennai,89,93,88,91
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78
13,ST014,Neha Desai,21,Surat,90,88,92,93
14,ST015,Manav Bansal,20,Noida,86,84,81,87
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95
18,ST019,Yash Thakur,22,Indore,75,70,78,82
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94
22,ST023,Varun Shetty,21,Mangaluru,69,73,67,72
23,ST024,Riya Choudhary,20,Patna,88,80,90,86
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
28,ST029,Karan Malhotra,21,Thane,80,71,82,85
29,ST030,Sneha Menon,20,Kochi,97,93,98,99

In [3]:
# Display the first 5 records
df.head()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
2,ST003,Rahul Verma,20,Delhi,76,81,73,79
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
4,ST005,Arjun Mehta,21,Pune,67,72,69,74

In [4]:
# Display the last 5 records.
df.tail()

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
28,ST029,Karan Malhotra,21,Thane,80,71,82,85
29,ST030,Sneha Menon,20,Kochi,97,93,98,99

In [5]:
# Display dataset shape.
df.shape

(30, 8)

In [6]:
# Display all column names.
df.columns

Index(['student_id', 'name', 'age', 'city', 'python_marks', 'sql_marks',
       'pandas_marks', 'attendance'],
      dtype='str')

In [7]:
# Display data types.
df.dtypes

student_id        str
name              str
age             int64
city              str
python_marks    int64
sql_marks       int64
pandas_marks    int64
attendance      int64
dtype: object

In [8]:
# Use info().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    30 non-null     str
 1   name          30 non-null     str
 2   age           30 non-null     int64
 3   city          30 non-null     str
 4   python_marks  30 non-null     int64
 5   sql_marks     30 non-null     int64
 6   pandas_marks  30 non-null     int64
 7   attendance    30 non-null     int64
dtypes: int64(5), str(3)
memory usage: 2.0 KB

In [9]:
# Use describe().
df.describe()

             age  python_marks  sql_marks  pandas_marks  attendance
count  30.000000     30.000000  30.000000     30.000000   30.000000
mean   20.933333     82.933333  81.966667     84.166667   86.833333
std     0.827682      8.800209   8.100589      8.391635    7.479090
min    20.000000     67.000000  68.000000     67.000000   72.000000
25%    20.000000     76.250000  75.250000     78.250000   81.250000
50%    21.000000     83.500000  82.500000     85.500000   87.500000
75%    22.000000     89.750000  88.750000     90.750000   92.750000
max    22.000000     97.000000  94.000000     98.000000   99.000000

In [10]:
# Find average Python marks.
df['python_marks'].mean()

np.float64(82.93333333333334)

In [11]:
# Find average SQL marks.
df['sql_marks'].mean()

np.float64(81.96666666666667)

In [12]:
# Find average Pandas marks.
df['pandas_marks'].mean()

np.float64(84.16666666666667)

In [13]:
# Find maximum marks.
df[['python_marks', 'sql_marks', 'pandas_marks']].max()

python_marks    97
sql_marks       94
pandas_marks    98
dtype: int64

In [14]:
# Find minimum marks.
df[['python_marks', 'sql_marks', 'pandas_marks']].min()

python_marks    67
sql_marks       68
pandas_marks    67
dtype: int64

In [15]:
# Sort students by Python marks.
df.sort_values(by='python_marks', ascending=False)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
29,ST030,Sneha Menon,20,Kochi,97,93,98,99
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94
13,ST014,Neha Desai,21,Surat,90,88,92,93
7,ST008,Meera Iyer,21,Chennai,89,93,88,91
23,ST024,Riya Choudhary,20,Patna,88,80,90,86
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91
14,ST015,Manav Bansal,20,Noida,86,84,81,87
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85
28,ST029,Karan Malhotra,21,Thane,80,71,82,85
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81
2,ST003,Rahul Verma,20,Delhi,76,81,73,79
18,ST019,Yash Thakur,22,Indore,75,70,78,82
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78
22,ST023,Varun Shetty,21,Mangaluru,69,73,67,72
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76
4,ST005,Arjun Mehta,21,Pune,67,72,69,74

In [16]:
# Sort students by attendance.
df.sort_values(by='attendance', ascending=False)

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
29,ST030,Sneha Menon,20,Kochi,97,93,98,99
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94
13,ST014,Neha Desai,21,Surat,90,88,92,93
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91
7,ST008,Meera Iyer,21,Chennai,89,93,88,91
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
14,ST015,Manav Bansal,20,Noida,86,84,81,87
23,ST024,Riya Choudhary,20,Patna,88,80,90,86
28,ST029,Karan Malhotra,21,Thane,80,71,82,85
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83
18,ST019,Yash Thakur,22,Indore,75,70,78,82
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80
2,ST003,Rahul Verma,20,Delhi,76,81,73,79
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76
4,ST005,Arjun Mehta,21,Pune,67,72,69,74
22,ST023,Varun Shetty,21,Mangaluru,69,73,67,72

In [17]:
# Filter students having Python marks greater than 80.
df[df['python_marks'] > 80]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85
7,ST008,Meera Iyer,21,Chennai,89,93,88,91
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89
13,ST014,Neha Desai,21,Surat,90,88,92,93
14,ST015,Manav Bansal,20,Noida,86,84,81,87
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94
23,ST024,Riya Choudhary,20,Patna,88,80,90,86
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
29,ST030,Sneha Menon,20,Kochi,97,93,98,99

In [18]:
# Filter students having attendance greater than 75.
df[df['attendance'] > 75]

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance
0,ST001,Aarav Sharma,20,Pune,85,78,91,88
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94
2,ST003,Rahul Verma,20,Delhi,76,81,73,79
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85
7,ST008,Meera Iyer,21,Chennai,89,93,88,91
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78
13,ST014,Neha Desai,21,Surat,90,88,92,93
14,ST015,Manav Bansal,20,Noida,86,84,81,87
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95
18,ST019,Yash Thakur,22,Indore,75,70,78,82
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94
23,ST024,Riya Choudhary,20,Patna,88,80,90,86
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89
28,ST029,Karan Malhotra,21,Thane,80,71,82,85
29,ST030,Sneha Menon,20,Kochi,97,93,98,99

In [19]:
# Select only name, python_marks, and pandas_marks.
df[['name', 'python_marks', 'pandas_marks']]

               name  python_marks  pandas_marks
0      Aarav Sharma            85            91
1      Ananya Patel            92            95
2       Rahul Verma            76            73
3        Priya Shah            88            86
4       Arjun Mehta            67            69
5         Diya Nair            94            90
6       Kabir Singh            81            84
7        Meera Iyer            89            88
8       Rohan Gupta            73            77
9      Sanya Kapoor            96            94
10     Vikram Joshi            78            80
11       Ishita Rao            84            87
12  Aditya Kulkarni            71            74
13       Neha Desai            90            92
14     Manav Bansal            86            81
15     Tanvi Mishra            79            83
16    Siddharth Roy            68            71
17      Kavya Reddy            93            96
18      Yash Thakur            75            78
19   Pooja Malhotra            87            89
20     Nikhil Sethi            82            85
21       Aisha Khan            91            93
22     Varun Shetty            69            67
23   Riya Choudhary            88            90
24      Dev Agarwal            77            79
25      Simran Kaur            95            91
26    Harsh Vardhan            74            76
27     Nandini Bose            83            86
28   Karan Malhotra            80            82
29      Sneha Menon            97            98

In [20]:
# Add a new column called total_marks.
df['total_marks'] = df[['python_marks', 'sql_marks', 'pandas_marks']].sum(axis=1)
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks
0,ST001,Aarav Sharma,20,Pune,85,78,91,88,254
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94,276
2,ST003,Rahul Verma,20,Delhi,76,81,73,79,230
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92,265
4,ST005,Arjun Mehta,21,Pune,67,72,69,74,208
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96,271
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85,240
7,ST008,Meera Iyer,21,Chennai,89,93,88,91,270
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80,218
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97,281
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83,240
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89,250
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78,221
13,ST014,Neha Desai,21,Surat,90,88,92,93,270
14,ST015,Manav Bansal,20,Noida,86,84,81,87,251
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90,247
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76,213
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95,279
18,ST019,Yash Thakur,22,Indore,75,70,78,82,223
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91,268
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84,244
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94,270
22,ST023,Varun Shetty,21,Mangaluru,69,73,67,72,209
23,ST024,Riya Choudhary,20,Patna,88,80,90,86,258
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81,239
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98,280
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77,219
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89,257
28,ST029,Karan Malhotra,21,Thane,80,71,82,85,233
29,ST030,Sneha Menon,20,Kochi,97,93,98,99,288

In [24]:
# Add another column called average_marks.
df['average_marks'] = df[['python_marks', 'sql_marks', 'pandas_marks']].mean(axis=1).round(2)
df

,student_id,name,age,city,python_marks,sql_marks,pandas_marks,attendance,total_marks,average_marks
0,ST001,Aarav Sharma,20,Pune,85,78,91,88,254,84.67
1,ST002,Ananya Patel,21,Mumbai,92,89,95,94,276,92.00
2,ST003,Rahul Verma,20,Delhi,76,81,73,79,230,76.67
3,ST004,Priya Shah,22,Ahmedabad,88,91,86,92,265,88.33
4,ST005,Arjun Mehta,21,Pune,67,72,69,74,208,69.33
5,ST006,Diya Nair,20,Bengaluru,94,87,90,96,271,90.33
6,ST007,Kabir Singh,22,Chandigarh,81,75,84,85,240,80.00
7,ST008,Meera Iyer,21,Chennai,89,93,88,91,270,90.00
8,ST009,Rohan Gupta,20,Jaipur,73,68,77,80,218,72.67
9,ST010,Sanya Kapoor,22,Hyderabad,96,91,94,97,281,93.67
10,ST011,Vikram Joshi,21,Nagpur,78,82,80,83,240,80.00
11,ST012,Ishita Rao,20,Kolkata,84,79,87,89,250,83.33
12,ST013,Aditya Kulkarni,22,Nashik,71,76,74,78,221,73.67
13,ST014,Neha Desai,21,Surat,90,88,92,93,270,90.00
14,ST015,Manav Bansal,20,Noida,86,84,81,87,251,83.67
15,ST016,Tanvi Mishra,22,Lucknow,79,85,83,90,247,82.33
16,ST017,Siddharth Roy,21,Kolkata,68,74,71,76,213,71.00
17,ST018,Kavya Reddy,20,Hyderabad,93,90,96,95,279,93.00
18,ST019,Yash Thakur,22,Indore,75,70,78,82,223,74.33
19,ST020,Pooja Malhotra,21,Gurugram,87,92,89,91,268,89.33
20,ST021,Nikhil Sethi,20,Amritsar,82,77,85,84,244,81.33
21,ST022,Aisha Khan,22,Bhopal,91,86,93,94,270,90.00
22,ST023,Varun Shetty,21,Mangaluru,69,73,67,72,209,69.67
23,ST024,Riya Choudhary,20,Patna,88,80,90,86,258,86.00
24,ST025,Dev Agarwal,22,Kanpur,77,83,79,81,239,79.67
25,ST026,Simran Kaur,21,Ludhiana,95,94,91,98,280,93.33
26,ST027,Harsh Vardhan,20,Ranchi,74,69,76,77,219,73.00
27,ST028,Nandini Bose,22,Bhubaneswar,83,88,86,89,257,85.67
28,ST029,Karan Malhotra,21,Thane,80,71,82,85,233,77.67
29,ST030,Sneha Menon,20,Kochi,97,93,98,99,288,96.00

In [25]:
df.to_csv('output/student_results.csv', index=False)